create table users (
    id bigint generated by default as identity primary key,
    email varchar(255) not null,
    display_name varchar(150) not null,
    active boolean not null default true,
    created_at timestamp with time zone not null default current_timestamp,
    updated_at timestamp with time zone not null default current_timestamp,

    constraint chk_users_email_not_blank
        check (length(trim(email)) > 0),

    constraint chk_users_display_name_not_blank
        check (length(trim(display_name)) > 0)
);

create unique index uk_users_email_lower
    on users (lower(email));

create table incidents (
    id bigint generated by default as identity primary key,
    title varchar(255) not null,
    description text not null,
    category varchar(100) not null,
    priority varchar(20) not null,
    status varchar(30) not null,
    reporter_id bigint not null,
    assignee_id bigint,
    created_at timestamp with time zone not null default current_timestamp,
    updated_at timestamp with time zone not null default current_timestamp,

    constraint fk_incidents_reporter
        foreign key (reporter_id) references users (id),

    constraint fk_incidents_assignee
        foreign key (assignee_id) references users (id),

    constraint chk_incidents_title_not_blank
        check (length(trim(title)) > 0),

    constraint chk_incidents_description_not_blank
        check (length(trim(description)) > 0),

    constraint chk_incidents_category_not_blank
        check (length(trim(category)) > 0),

    constraint chk_incidents_priority
        check (priority in ('LOW', 'MEDIUM', 'HIGH', 'CRITICAL')),

    constraint chk_incidents_status
        check (status in ('OPEN', 'ASSIGNED', 'IN_PROGRESS', 'RESOLVED', 'CLOSED', 'CANCELLED'))
);

create index idx_incidents_reporter_id
    on incidents (reporter_id);

create index idx_incidents_assignee_id
    on incidents (assignee_id);

create index idx_incidents_created_at
    on incidents (created_at);
