do $$
declare
    unknown_categories text;
begin
    select string_agg(category, ', ' order by category)
    into unknown_categories
    from (
        select distinct category
        from incidents
        where lower(btrim(category)) not in (
            'infrastructure',
            'hardware',
            'application',
            'software',
            'business_process'
        )
    ) unknown_values;

    if unknown_categories is not null then
        raise exception
            'Unknown incident categories require explicit mapping: %',
            unknown_categories;
    end if;
end
$$;

create table teams (
    id bigint generated by default as identity primary key,
    name varchar(150) not null,
    code varchar(50) not null,
    active boolean not null default true,
    created_at timestamp with time zone not null default current_timestamp,
    updated_at timestamp with time zone not null default current_timestamp,

    constraint chk_teams_name_not_blank
        check (length(btrim(name)) > 0),

    constraint chk_teams_code_not_blank
        check (length(btrim(code)) > 0)
);

create unique index uk_teams_code_normalized
    on teams (lower(btrim(code)));

alter table incidents
    add column source varchar(20);

update incidents
set source = 'MANUAL'
where source is null;

alter table incidents
    alter column source set not null;

alter table incidents
    add constraint chk_incidents_source
        check (source in ('MANUAL', 'AUTOMATIC'));

update incidents
set category = case lower(btrim(category))
    when 'infrastructure' then 'INFRASTRUCTURE'
    when 'hardware' then 'INFRASTRUCTURE'
    when 'application' then 'APPLICATION'
    when 'software' then 'APPLICATION'
    when 'business_process' then 'BUSINESS_PROCESS'
end;

alter table incidents
    drop constraint chk_incidents_category_not_blank;

alter table incidents
    alter column category type varchar(30);

alter table incidents
    add constraint chk_incidents_category
        check (category in ('INFRASTRUCTURE', 'APPLICATION', 'BUSINESS_PROCESS'));

alter table incidents
    add column responsible_team_id bigint;

alter table incidents
    add constraint fk_incidents_responsible_team
        foreign key (responsible_team_id) references teams (id);

create index idx_incidents_responsible_team_id
    on incidents (responsible_team_id);
