create table incident_audit_events (
    id bigint generated by default as identity primary key,
    incident_id bigint not null,
    event_type varchar(30) not null,
    from_status varchar(30),
    to_status varchar(30) not null,
    created_at timestamp with time zone not null default current_timestamp,

    constraint fk_incident_audit_events_incident
        foreign key (incident_id) references incidents (id),

    constraint chk_incident_audit_events_event_type
        check (event_type in ('CREATED', 'ASSIGNED', 'STARTED', 'RESOLVED', 'REOPENED', 'CLOSED', 'CANCELLED')),

    constraint chk_incident_audit_events_from_status
        check (from_status is null or from_status in ('OPEN', 'ASSIGNED', 'IN_PROGRESS', 'RESOLVED', 'CLOSED', 'CANCELLED')),

    constraint chk_incident_audit_events_to_status
        check (to_status in ('OPEN', 'ASSIGNED', 'IN_PROGRESS', 'RESOLVED', 'CLOSED', 'CANCELLED')),

    constraint chk_incident_audit_events_created_from_status
        check ((event_type = 'CREATED' and from_status is null) or (event_type <> 'CREATED' and from_status is not null))
);

create index idx_incident_audit_events_incident_created_id
    on incident_audit_events (incident_id, created_at, id);
