create table business_services (
    id bigint generated by default as identity primary key,
    code varchar(50) not null,
    name varchar(150) not null,
    description text not null,
    owner_team_id bigint not null,
    tier varchar(20) not null,
    active boolean not null default true,
    created_at timestamp with time zone not null default current_timestamp,
    updated_at timestamp with time zone not null default current_timestamp,

    constraint fk_business_services_owner_team
        foreign key (owner_team_id) references teams (id),

    constraint chk_business_services_code_not_blank
        check (length(btrim(code)) > 0),

    constraint chk_business_services_name_not_blank
        check (length(btrim(name)) > 0),

    constraint chk_business_services_description_not_blank
        check (length(btrim(description)) > 0),

    constraint chk_business_services_tier
        check (tier in ('TIER_1', 'TIER_2', 'TIER_3'))
);

create unique index uk_business_services_code_normalized
    on business_services (lower(btrim(code)));

create index idx_business_services_owner_team_id
    on business_services (owner_team_id);

create table service_dependencies (
    id bigint generated by default as identity primary key,
    dependent_id bigint not null,
    dependency_id bigint not null,
    type varchar(20) not null,
    created_at timestamp with time zone not null default current_timestamp,

    constraint fk_service_dependencies_dependent
        foreign key (dependent_id) references business_services (id),

    constraint fk_service_dependencies_dependency
        foreign key (dependency_id) references business_services (id),

    constraint uk_service_dependencies_pair
        unique (dependent_id, dependency_id),

    constraint chk_service_dependencies_no_self_reference
        check (dependent_id <> dependency_id),

    constraint chk_service_dependencies_type
        check (type in ('SYNC', 'ASYNC', 'DATA'))
);

create index idx_service_dependencies_dependent_id
    on service_dependencies (dependent_id);

create index idx_service_dependencies_dependency_id
    on service_dependencies (dependency_id);
